services:
  db:
    image: postgres:latest
    container_name: orders_db
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: orders_db
    ports:
      - "5432:5432"

  redis:
    image: redis:latest
    container_name: orders_cache
    restart: always
    ports:
      - "6379:6379"
      # TODO попробовать добавить запуск приложения в этот файл