apiVersion: v1
kind: Secret
metadata:
  name: orders-secrets
  namespace: orders
type: Opaque
stringData:
  POSTGRES_USER: "user"
  POSTGRES_PASSWORD: "password"
  POSTGRES_DB: "orders_db"
  CONNECTION_STRING: "Host=orders-db;Database=orders_db;Username=user;Password=password"
  REDIS_CONNECTION: "orders-redis:6379"