apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: orders-keyvault
  namespace: {{ .Values.namespace }}
spec:
  provider: azure
  secretObjects:
    - secretName: orders-secrets
      type: Opaque
      data:
        - objectName: POSTGRES-USER
          key: POSTGRES_USER
        - objectName: POSTGRES-PASSWORD
          key: POSTGRES_PASSWORD
        - objectName: POSTGRES-DB
          key: POSTGRES_DB
        - objectName: CONNECTION-STRING
          key: CONNECTION_STRING
        - objectName: REDIS-CONNECTION
          key: REDIS_CONNECTION
        - objectName: JWT-KEY
          key: JWT_KEY
  parameters:
    usePodIdentity: "false"
    clientID: "a4fe10f0-efbd-4d35-9804-8362ed17f828"
    keyvaultName: "orders-kv"
    tenantId: "c6bbf2ff-cd5d-4c41-a0e5-fa73202de5e9"
    objects: |
      array:
        - |
          objectName: POSTGRES-USER
          objectType: secret
        - |
          objectName: POSTGRES-PASSWORD
          objectType: secret
        - |
          objectName: POSTGRES-DB
          objectType: secret
        - |
          objectName: CONNECTION-STRING
          objectType: secret
        - |
          objectName: REDIS-CONNECTION
          objectType: secret
        - |
          objectName: JWT-KEY
          objectType: secret
