apiVersion: v1
kind: Secret
metadata:
  name: orders-secrets
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
  POSTGRES_USER: {{ .Values.secrets.postgresUser | quote }}
  POSTGRES_PASSWORD: {{ .Values.secrets.postgresPassword | quote }}
  POSTGRES_DB: {{ .Values.secrets.postgresDb | quote }}
  CONNECTION_STRING: {{ .Values.secrets.connectionString | quote }}
  REDIS_CONNECTION: {{ .Values.secrets.redisConnection | quote }}
  JWT_KEY: {{ .Values.secrets.jwtKey | quote }}
