apiVersion: v1
kind: ServiceAccount
metadata:
  name: orders-service-account
  namespace: {{ .Values.namespace }}
  annotations:
    azure.workload.identity/client-id: "c0a2b2a4-92b6-44bd-ae80-42ad8132033e"
