name: .NET CI

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

defaults:
      run:
        working-directory: ./WebApplication1 


    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore

    - name: Test with Coverage
      run: dotnet test --no-restore --verbosity normal --collect:"XPlat Code Coverage"

    - name: Upload Coverage Results
      uses: actions/upload-artifact@v4
      with:
        name: code-coverage-report
        path: "**/TestResults/**/coverage.cobertura.xml"